### ISSUE TITLE
Layout Components

### ISSUE THREAD

**Issue by wheregmis** [DioxusLabs/components#1]
Are we planning to have basic layout components like Rows and Columns in the component library? I was building basic components for personal use, i can try to create a pr for those, if its still in the scope of the project

**Comment by DogeDark** [comment]
I haven't thought much about layout stuff just yet. Having flexbox-based rows and columns would be nice. You are welcome to create PR but currently, the SCSS building only works on Windows - I'm planning on fixing this next.

**Comment by wheregmis** [comment]
I was able to use sass building on mac, and fix the css output by using include_str instead of magnis as of now.    std::process::Command::new("sass.cmd") to    std::process::Command::new("sass") made it work with Mac. I will try to push Column and Row for layout soon just for the review.
